apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: basilisk-api-app
  labels:
    cloud.googleapis.com/location: europe-west3

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "30"
        run.googleapis.com/vpc-access-connector: basilisk-api-connector

    spec:
      timeoutSeconds: "10"
      containers:
        - image: europe-west3-docker.pkg.dev/production-basilisk-api/basilisk-api/basilisk-api-app:latest
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
